OUTPUT_DIR: "models/toy/output"
MODEL:
    META_ARCHITECTURE: "Model"
    PIXEL_MEAN: [123.675, 116.280, 103.530]
    PIXEL_STD: [58.395, 57.120, 57.375]
    WEIGHTS: ""
    MASK_ON: true
    RESNETS:
        DEPTH: 50
        OUT_FEATURES: ["res2", "res3", "res4", "res5"]
DATASETS:
    TRAIN: ("mock_train",)
    TEST: ("mock_test",)
    ROOT: "assets/datasets"
DATALOADER:
    NUM_WORKERS: 4
SOLVER:
    AMP:
        ENABLED: true
    BACKBONE_MULTIPLIER: 1.0
    BASE_LR: 0.0001
    CHECKPOINT_PERIOD: 10000
    CLIP_GRADIENTS:
        CLIP_TYPE: full_model
        CLIP_VALUE: 5.0
        ENABLED: true
        NORM_TYPE: 2.0
    GAMMA: 0.1
    IMS_PER_GPU: 8
    NUM_GPUS: 1
    LR_SCHEDULER_NAME: WarmupMultiStepLR
    MOMENTUM: 0.9
    OPTIMIZER: ADAMW
    STEPS: (20000,)
    MAX_ITER: 30000
    REFERENCE_WORLD_SIZE: 0
    WARMUP_FACTOR: 1.0
    WARMUP_ITERS: 100
    WEIGHT_DECAY: 0.0001
    WEIGHT_DECAY_EMBED: 0.0
    WEIGHT_DECAY_NORM: 0.0
INPUT:
    TRAIN_RESOLUTION: 800
    TEST_RESOLUTION: 800
TEST:
    EVAL_PERIOD: 1000
    AUG:
        ENABLED: false
VERSION: 2
